name: Send Email on Push

on:
  push:
    branches:
      - main  # Change this to your branch name if needed

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: alroy17gama@gmail.com
          password: bankuras27
          subject: "GitHub Push Notification"
          body: "A push has been made to the branch main!"
          to: goconutgoa@gmail.com
          from: alroy17gama@gmail.com
