name: Send Email on Push

on:
  push:
    branches:
      - main  # Change this to your branch name if needed

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Commit Information
        id: commit_info
        run: |
          echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "COMMIT_EMAIL=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
          echo "COMMIT_DATE=$(git log -1 --pretty=format:'%ad' --date=iso)" >> $GITHUB_ENV

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: alroy17gama@gmail.com
          password: gpfo fomx bakl gbyj  # Replace with your actual app-specific password
          subject: "GitHub Push Notification to main branch"
          body: |
            A push has been made to the branch **main**.

            **Commit Details:**
            - **Author:** ${{ env.COMMIT_AUTHOR }}
            - **Email:** ${{ env.COMMIT_EMAIL }}
            - **Message:** ${{ env.COMMIT_MESSAGE }}
            - **Date:** ${{ env.COMMIT_DATE }}
            
            **Repository Information:**
            - **Branch:** ${{ github.ref_name }}
            - **Repository:** ${{ github.repository }}
          to: goconutgoa@gmail.com
          from: alroy17gama@gmail.com
